ci: add testground detect failure

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -111,4 +111,32 @@ jobs:
             --builder=docker:generic \
             --runner=local:docker \
             --instances=1 \
-            --wait
+            --wait | tee run.out
+      - name: Check testground output (sdk-rust)
+        run: |
+          TG_ID=$(awk '/run is queued with ID/ {print $10}' <run.out)
+          testground status -t "${TG_ID}" --extended  | tee extendedstatus.out
+          extstatus=$(awk '/Result/ {getline; print $0}' <extendedstatus.out)
+          extstatus=$(echo "${extstatus}" | tr -d "[:cntrl:]" |  sed 's/\[0m//g')
+          if [ "${extstatus}" == "null" ]
+          then
+            echo "${OUTPUT_OUTCOME}failure/canceled"
+            exit 1
+          fi
+
+          outcome=$(echo "${extstatus}" | jq ".outcome")
+
+          echo "the extended status was ${extstatus}"
+          echo "The outcome of this test was ${outcome}"
+          echo "${OUTPUT_OUTCOME}${outcome}"
+
+          testground collect --runner "${TG_RUNNER}" "${TG_ID}"
+          mv "${TG_ID}.tgz" ~/testground_output.tgz
+
+          test "${outcome}" = "\"success\"" && exit 0 || exit 1
+      - uses: actions/upload-artifact@v3
+        if: ${{ always() }}
+        with:
+          name: testground-output
+          path: |
+            ~/testground_output.tgz
